### ISSUE TITLE
Failed to connect VTTablet 

### ISSUE THREAD

**Issue by dongbin** [vtdriverio/vtdriver#1]
Vitess 0.12, and keep getting errors: 

Nov 26, 2021 3:51:48 PM io.vitess.shaded.io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
SEVERE: *~*~*~ Channel ManagedChannelImpl{logId=23354, target=10.224.72.227:15999} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
        at io.vitess.shaded.io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:93)
        at io.vitess.shaded.io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:53)
        at io.vitess.shaded.io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:44)
        at io.vitess.shaded.io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:596)
        at io.vitess.shaded.io.grpc.ForwardingChannelBuilder.build(ForwardingChannelBuilder.java:255)
        at com.jd.jdbc.queryservice.TabletDialer.dial(TabletDialer.java:49)
        at com.jd.jdbc.discovery.TabletHealthCheck.getTabletQueryServiceLocked(TabletHealthCheck.java:132)
        at com.jd.jdbc.discovery.TabletHealthCheck.getHealthCheckQueryService(TabletHealthCheck.java:121)
        at com.jd.jdbc.discovery.TabletHealthCheck.startHealthCheckStream(TabletHealthCheck.java:217)
        at com.jd.jdbc.discovery.HealthCheck$1.lambda$run$0(HealthCheck.java:410)
        at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
        at com.jd.jdbc.discovery.HealthCheck$1.run(HealthCheck.java:383)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
        at java.base/java.util.TimerThread.run(Timer.java:506)

**Comment by TDavid2509** [comment]
> ManagedChannel allocation site

Hi DongBin,

Thanks for your report. Could you please provide more detail, such as complete Exception stack, database configuration? 

According to our experience, this error is caused by an unauthorized database account.

If you use a vitess account to connect, you need to configure MySQL to allow this account to access the data node directly. There is a [sample script](https://github.com/vtdriverio/vtdriver/blob/main/src/test/resources/config/init_mysql_user.sh) and [quick-start](https://github.com/vtdriverio/vtdriver/blob/main/docs/QuickStart.md). Hope it can be useful for you.

**Comment by wanghaoyang1995** [comment]
@dongbin Hi, dongbin!

Now we provid a docker image for vtdriver, you can build it easily with only two command as following:
```bash
git clone git@github.com:vtdriverio/vtdriver.git
cd vtdriver/src/test/resource/vitess_env
./setup.sh

# wait few minutes...
docker run -e HOST_IP=127.0.0.1 -it --name=vtdriver-env -p16100:16100 -p16101:16101 -p16102:16102 -p16300:16300 -p16301:16301 -p16302:16302 -p16400:16400 -p16401:16401 -p16402:16402 -p15000:15000 -p15001:15001 -p15306:15306 -p15100:15100 -p15101:15101 -p15102:15102 -p15300:15300 -p15301:15301 -p15302:15302 -p15400:15400 -p15401:15401 -p15402:15402 -p2379:2379 -p17100:17100 -p17101:17101 -p17102:17102 -p17300:17300 -p17301:17301 -p17302:17302 -p17400:17400 -p17401:17401 -p17402:17402 vitess/vtdriver-env:latest

# or in a no-macos computer
docker run -e HOST_IP=<服务器IP> -itd --name=vtdriver-env --network=host vitess/vtdriver-env:latest
```
More details are in https://github.com/vtdriverio/vtdriver/blob/main/docs/QuickStart.md

Thank you for your report!
